### PR TITLE
 finish of the stepper

### LINKED ISSUE #178: (SP: 2) Implement finish of the stepper
UserStory: #65 , #64
Blocked by: #177 

## Description
Implement sending all data to server besides photo by finishing

## Design 

Image

## Acceptance Criteria
- [ ] When user click finish it should send collected data from stepper to user
- [ ] If user haven't filled required fields it shouldn't be sent to server
- [ ] Stepper title that has errors with not filed required fields should has red color

### PR DESCRIPTION
**Pull request by YaroslavChuiko**
[screen-capture (1).webm](https://github.com/Space2Study-UA-1156/Client-01/assets/32570823/11d24591-6168-4be3-836d-87bf3abe2900)

### CODE REVIEW

**Review by YaroslavLys — APPROVED** [review]

**Review by OlhaOvsiienko — APPROVED** [review]

**Review by voloshynvv — COMMENTED** [review]
You forgot to add a photo from context, please add it to the params

photo

**Comment by YaroslavChuiko** [comment]
> You forgot to add a photo from context, please add it to the params
> 
> photo

if I do this, the server will send 500 in response
image

**Comment by voloshynvv** [comment]
I was working on photo uploading
pull the latest changes, the error should disappear

git checkout develop (on the backend)
git pull

**Review by YaroslavLys — APPROVED** [review]

**Review by voloshynvv — APPROVED** [review]

**Review by holus-bolus — APPROVED** [review]

**Review by vlad-khrychov — APPROVED** [review]
Are we losing coverage, are you planning to change the tests?

**Pull request merged**
